"""empty message

Revision ID: 01a5a06d651f
Revises: 6bbb4776c738
Create Date: 2023-06-30 16:45:01.643590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a5a06d651f'
down_revision = '6bbb4776c738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_ong', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('codigo_ong')

    # ### end Alembic commands ###
