"""empty message

Revision ID: 04ccd4a42b58
Revises: 195f341858a8
Create Date: 2023-07-09 13:03:06.395656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ccd4a42b58'
down_revision = '195f341858a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=80), nullable=True))
        batch_op.drop_column('dirección')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dirección', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
