"""empty message

Revision ID: 6bbb4776c738
Revises: f53899d3e26f
Create Date: 2023-06-28 19:26:18.700913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbb4776c738'
down_revision = 'f53899d3e26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ong', sa.Integer(), nullable=True))
        batch_op.drop_constraint('recurso_ong_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ong', ['ong'], ['id'])
        batch_op.drop_column('ong_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ong_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recurso_ong_id_fkey', 'ong', ['ong_id'], ['id'])
        batch_op.drop_column('ong')

    # ### end Alembic commands ###
