"""empty message

Revision ID: 77f4b35c4e0d
Revises: 01a5a06d651f
Create Date: 2023-06-30 18:18:34.615235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f4b35c4e0d'
down_revision = '01a5a06d651f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('codigo_ong')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_ong', sa.VARCHAR(length=30), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
