"""empty message

Revision ID: bd44bffa9164
Revises: ca2fcf5f3dbc
Create Date: 2023-07-04 14:01:50.839845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd44bffa9164'
down_revision = 'ca2fcf5f3dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ong_id', sa.String(length=300), nullable=False))
        batch_op.create_unique_constraint(None, ['ong_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ong_id')

    # ### end Alembic commands ###
