"""empty message

Revision ID: d577bc823f1e
Revises: 04ccd4a42b58
Create Date: 2023-07-09 14:17:55.684197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd577bc823f1e'
down_revision = '04ccd4a42b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ong_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('recurso_ong_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ong', ['ong_id'], ['id'])
        batch_op.drop_column('ong')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurso', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ong', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recurso_ong_fkey', 'ong', ['ong'], ['id'])
        batch_op.drop_column('ong_id')

    # ### end Alembic commands ###
