"""empty message

Revision ID: f53899d3e26f
Revises: 8b2892ab381e
Create Date: 2023-06-28 17:47:04.970353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53899d3e26f'
down_revision = '8b2892ab381e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ong_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['ong_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ong_id')

    # ### end Alembic commands ###
